config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  root to: "topics#index"

  resources :topics do
  	resources :posts
  end

end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/post.rb
class Post < ActiveRecord::Base
  belongs_to :topic
  belongs_to :user
end

app/models/topic.rb
class Topic < ActiveRecord::Base
  has_many :posts
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  has_many :posts
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :authenticate_user!
  protect_from_forgery with: :exception

end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
	def new
		@topic = Topic.find(params[:topic_id])
		@post = Post.new
	end
	def show
		@topic = Topic.find(params[:topic_id])
		@post = Post.find(params[:id])
	end
	def create
		@topic = Topic.find(params[:topic_id])
		@post = @topic.posts.create(post_params.merge(user:current_user))
		redirect_to topic_path(@topic)
	end
	def edit
		@topic = Topic.find(params[:topic_id])
		@post = Post.find(params[:id])

	end
	def update
		@topic = Topic.find(params[:topic_id])
		@post = Post.find(params[:id])
		@post.update(post_params.merge(user:current_user))
		redirect_to topic_path(@topic)
	end
	def destroy
		@topic = Topic.find(params[:topic_id])
		@post = Post.find(params[:id])
		@post.destroy
		redirect_to topic_path(@topic)
	end

private
def post_params
  params.require(:post).permit(:title, :text, :source)
end
end

app/controllers/topics_controller.rb
class TopicsController < ApplicationController

def index
	@topics = Topic.all
end
 #show
def show
	@topics = Topic.find(params[:id])
end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
    <head>
        <title>Stump.me - Talking points in your pocket.</title>
        <%= csrf_meta_tags %>
        <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
        <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
        <meta name="viewport" content="width=device-width, initial-scale=1">
        <link href="https://fonts.googleapis.com/css?family=Karla|Nunito" rel="stylesheet">
    </head>
    <div class="container">
        <div class="nav-container">
          <div class="nav-left">
            <a href="/" class='home-link'>Stump.me</a>
            <h2>Pocket-sized talking points <br>for your next stump speech</h2>
          </div>
            <ul class="nav-right">
                <% if !current_user %>
                <li><%= link_to "Sign Up", new_user_registration_path, class: "glyphicon glyphicon-user" %></li>
                <li><%= link_to "Sign In", new_user_session_path, class: "glyphicon glyphicon-log-in" %></li>
            <% else %>
                <%= link_to "Log Out", destroy_user_session_path, :method => :delete %>
                <%= current_user.email %>
                <% end %>
                <p class="notice"><%= notice %></p>
                <p class="alert"><%= alert %></p>
            </ul>
        </div>
        <%= yield %>
    </div>
</html>

app/views/posts/edit.html.erb
<div class="form">
  <h1>Edit "<%=@post.title%>"</h1>
    <%= form_for [@topic, @post] do |f| %>
    <%= f.label :title %>
    <%= f.text_field :title %>

    <%= f.label :text %>
    <%= f.text_field :text %>

    <%= f.label :source %>
    <%= f.text_field :source %>

      <%= f.submit "Edit" %>
    <% end %>
</div>

app/views/posts/new.html.erb
<div class="form">
	<h1>Create New Post for <%=@topic.subject_name%></h1>
	<%= form_for [@topic, @post] do |f| %>
		  <%= f.label :title %>
		  <%= f.text_field :title %>

		  <%= f.label :text %>
		  <%= f.text_field :text %>

		  <%= f.label :source %>
		  <%= f.text_field :source %>

			<%= f.submit %>
	<% end %>
</div>

app/views/posts/show.html.erb
<div class="postCard"><h1><%= @post.title %></h1>
  <h5>Summary</h5>
    <h6><%= @post.text %></h6>
  <h5>Source</h5>
     <h6><a href="<%= @post.source %>"</a><%= @post.source %></h6>
  <div class="button"> <%=link_to "Edit", edit_topic_post_path %></div>
  <div class="button"><%=link_to "Delete", topic_post_path(@topic, @post), method: :delete %></div>
</div>

app/views/topics/index.html.erb
<div class="issues-container">
  <% @topics.each do |topic| %>
      <div class="thumbnail" style ="background: url('<%= topic.img_url %>');background-size: cover;" alt="<%= topic.subject_name %>">
        <a href="/topics/<%= topic.id %>" class="subject-name">
          <%= topic.subject_name %>
      </div>
    </a>
      <% end %>
</div>

app/views/topics/show.html.erb
<div class="topic-container">
    <h3><%=@topics.subject_name %> &nbsp; <span class="add-link"><%=link_to "+", new_topic_post_path(@topics) %></span></h3>
    <img src="<%= @topics.img_url %>"/>
            <ul>
                <% @topics.posts.each do |post| %>
                    <a href="/topics/<%=@topics.id %>/posts/<%= post.id %>" class="postLink">
                        <%= "#{post.title}" %>
                    </a>
                <% end %>
            </ul>
</div>